[project]
name = "5dgai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.1",
    "backoff>=2.2.1",
    "google-adk>=1.18.0",
    "litellm[proxy]>=1.79.3",
    "orjson>=3.11.4",
]
